default: &default
  adapter: postgresql
  username: postgres
  password: a1!@!@
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: scraper_development

test:
  <<: *default
  database: scraper_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>